const CREATE_TODO = 'CREATE/TODO';
const DELETE_TODO = 'DELETE/TODO';
const DELETE_TODO_COMPLETED = 'DELETE/TODO/COMPLETED';
const UPDATE_TODO = 'UPDATE/TODO';
const GET_TODO_LIST = 'GET/TODO';

const STATUS = {
  UNCOMPLETED: 0,
  COMPLETED: 1,
}

const TODOLIST_TYPE = {
  ALL: 'all',
  UNCOMPLETED: 'uncompleted',
  COMPLETED: 'completed'
}


export {
  CREATE_TODO,
  DELETE_TODO,
  DELETE_TODO_COMPLETED,
  UPDATE_TODO,
  GET_TODO_LIST,
  STATUS,
  TODOLIST_TYPE,
};